<?php $_SESSION[tn]=EN;?>
<!doctype html>
<html> 
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title></title>
<link rel="stylesheet" href="css/pure-min.css">
<link rel="stylesheet" href="css/side-menu.css">

</head>
<body>

<div id="layout">
    <a href="#menu" id="menuLink" class="menu-link">
        <span></span>
    </a>
    <div id="menu">
        <div class="pure-menu pure-menu-open">
            <a class="pure-menu-heading" href="#">Menu</a>

            <ul>
				<li><a href="index.php" data-ajax="false">xls form design method</a></li>
				<li><a href="background.html" data-ajax="false">Background pictures</a></li>
				<li><a href="design.php" data-ajax="false">App design upload page</a></li>
				<li><a href="designmenu.php" data-ajax="false">Navigation Menu for sub-apps</a></li>
				<li class="menu-item-divided pure-menu-selected"><a href="explanation.php" data-ajax="false">Explanation</a></li>
            </ul>
        </div>
    </div>
    <div id="main">
        <div class="header" style="background-color:#0098FF">          
            <h2>AppMoney712 App Creation System</h2>
        </div>

        <div class="content">
		
	
	
	<h2 style="color:#000000"><?php if($_SESSION[tn]==PRC){echo '';}else if($_SESSION[tn]==EN){echo 'Contact';}else{echo '';}?></h2>
	<a href="mailto:contact@appmoney712.net" class="pure-button pure-button-primary">contact@appmoney712.net</a><hr>
	
	<h2 style="color:#000000">AppMoney712 JQMPIG FRAMEWORK<BR>- AppMoney712 App Creation System</h2>
	
	<h2 style="color:#000000"><?php if($_SESSION[tn]==PRC){echo '';}else if($_SESSION[tn]==EN){echo 'Software License';}else{echo '';}?></h2>
	Only donator can use this software for commerical use under MIT license and without distribution and/or sell privileges. Please refer to our website www.appmoney712.net.<br>
	<h2 style="color:#000000">Source code license - Explanation</h2>
	 The purpose of the software is to create app pages. The software can generate app pages which are same license as your app generated by the website. Please refer to the explanation on our website www.appmoney712.net.
	 You own the copyright of content and source code you develop in this software output e.g. data or app page.<br>
	 You need to keep your paypal or alipay payment receipt(s).<br>
	 Free of charge mentioned in MIT license is waived due to donation. The donation fee is not tax free in Hong Kong and is not refundable.<br>
	 Distribute and/or sell condition mentioned in MIT license are waived.<br>
	 You can use it in any Internet environment/Intranet environment/PHP environment to create app pages at any time only for the donation giving.<br>
	 
	 <hr>
	<h2 style="color:#000000"><?php if($_SESSION[tn]==PRC){echo '';}else if($_SESSION[tn]==EN){echo 'Distribution and sell explanation';}else{echo '';}?></h2>
	You need this system to create your apps but you do not need to distribute this app creation software to your users.
	<hr>
	
	<h2 style="color:#000000"><?php if($_SESSION[tn]==PRC){echo '';}else if($_SESSION[tn]==EN){echo 'License of Software output';}else{echo '';}?></h2>
	The software can generate app pages which are same license as the app generated by the website. Please refer to our website www.appmoney712.net.
	<hr>
	<div class="copyright">&copy; 2014 Lee Wai Kwok(Hong Kong). JSTRUST CONSULTANCY. All Rights Reserved.</div>
	
</div>   
    </div>
</div>

</body>
</html>

<script>

</script>
