<?php $_SESSION[tn]=EN;?>
<!DOCTYPE html> 
	<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style">
	<title></title>
	<link rel="stylesheet" href="css/jquerymobile-1.4.0.min.css">
	<link rel="stylesheet" href="css/jquery.mobile-1.4.0.min.css">
	<link rel="stylesheet" href="css/jqmobile.min.css">
	<link href="css/mtnpjhsp.css" rel="stylesheet">
	<link href="css/icons/icon.css" rel="stylesheet">
	<link rel="shortcut icon" href="favicon.ico">
	<!--wettopbr--><style type="text/css">
	</style><!--copyiframes-->
	<script src="js/jquery.js"></script>
	<script src="js/jquery.mobile-1.4.0.min.js"></script>
	<!--copyiframe--><!--copyiframes-->

</head>
	<body><div data-role="page" data-theme="f" class="page indexhtml">
	<div  data-role="header" id="hrdiv" data-theme="f"><h1 id="hrs">AppMoney712 App Creation System</h1><a href="index.php"  data-ajax="false" class="ui-btn-left ui-btn ui-btn-inline ui-corner-all ui-btn-icon-left ui-icon-home">&nbsp;&nbsp;&nbsp;</a>
	</div><!-- /header --><div data-role="content" class="pagebg"><!--copyiframe--><!-- /content!-->

	
	<h2 style="color:#000000"><?php if($_SESSION[tn]==PRC){echo '';}else if($_SESSION[tn]==EN){echo 'Contact';}else{echo '';}?></h2>
	<a href="mailto:contact@appmoney712.net" class="ui-btn ui-btn-f ui-btn-inline">contact@appmoney712.net</a><hr>
	
	<h2 style="color:#000000">AppMoney712 JQMPIG FRAMEWORK - AppMoney712 App Creation System</h2>
	
	<h2 style="color:#000000"><?php if($_SESSION[tn]==PRC){echo '';}else if($_SESSION[tn]==EN){echo 'Software License';}else{echo '';}?></h2>
	Only donator can use this software for commerical use under MIT license and without distribution and/or sell privileges. Please refer to our website www.appmoney712.net.<br>
	<h2 style="color:#000000">Source code license - Explanation</h2>
	 The purpose of the software is to create app pages. The software can generate app pages which are same license as your app generated by the website. Please refer to the explanation on our website www.appmoney712.net.
	 You own the copyright of content and source code you develop in this software output e.g. data or app page.<br>
	 You need to keep your paypal or alipay payment receipt(s).<br>
	 Free of charge mentioned in MIT license is waived due to donation. The donation fee is not tax free in Hong Kong and is not refundable.<br>
	 Distribute and/or sell condition mentioned in MIT license are waived.<br>
	 You can use it in any Internet environment/Intranet environment/PHP environment to create app pages at any time only for the donation giving.<br>
	 
	 <hr>
	<h2 style="color:#000000"><?php if($_SESSION[tn]==PRC){echo '';}else if($_SESSION[tn]==EN){echo 'Distribution and sell explanation';}else{echo '';}?></h2>
	You need this system to create your apps but you do not need to distribute this app creation software to your users.
	<hr>
	
	<h2 style="color:#000000"><?php if($_SESSION[tn]==PRC){echo '';}else if($_SESSION[tn]==EN){echo 'License of Software output';}else{echo '';}?></h2>
	The software can generate app pages which are same license as the app generated by the website. Please refer to our website www.appmoney712.net.
	<hr>
	<div class="copyright">&copy; 2014 Lee Wai Kwok(Hong Kong). JSTRUST CONSULTANCY. All Rights Reserved.</div>
	
	</div>
	
	
	</div>
</div>
</body></html>

<script>

</script>
